# Generated by Django 2.2 on 2020-11-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20190414_1350'),
        ('perfis', '0003_auto_20200829_0022'),
    ]

    operations = [
    ]
